### ISSUE TITLE
random failure with connext and opensplice

### ISSUE THREAD

**Issue by wjwwood** [ros2/system_tests#37] opened 2015-08-26 21:24 UTC
Between two Linux builds which were expected to be the same this test failed:

http://ci.ros2.org/job/ros2_batch_ci_linux/274/testReport/junit/(root)/test_requester_replier_cpp__primitives__rmw_connext_dynamic_cpp__rmw_connext_cpp/test_requester_replier/

The previous build passed: http://ci.ros2.org/job/ros2_batch_ci_linux/273/

Some of the output seems to indicate a similar failure (maybe not a common cause) to this: https://community.rti.com/kb/osx510

**Comment by tfoote** [comment] 2015-08-28 21:03
This same test appears to be flaky on opensplice with a different error on osx: http://ci.ros2.org/job/ros2_batch_ci_osx/218/testReport/junit/%28root%29/test_requester_replier_cpp__primitives__rmw_opensplice_cpp/test_requester_replier/

**Comment by jacquelinekay** [comment] 2015-10-15 21:10
Duplicate of ros2/ros2#127

**Closed** 2015-10-15 21:12 UTC
Labels: duplicate
