### ISSUE TITLE
New nightly test failures in test_communication

### ISSUE THREAD

**Issue by mjcarroll** [ros2/system_tests#399] opened 2020-02-12 15:15 UTC
There are new test failures in the linux nightly build:

First failures: https://ci.ros2.org/view/nightly/job/nightly_linux_debug/1456/ (Feb 11, 2020)

Failures are:

```
test_communication.TestPublisherSubscriber.test_subscriber_terminates_in_a_finite_amount_of_time[Arrays]
test_communication.TestPublisherSubscriber.test_subscriber_terminates_in_a_finite_amount_of_time[BasicTypes]
test_communication.TestPublisherSubscriber.test_subscriber_terminates_in_a_finite_amount_of_time[BoundedSequences]
test_communication.TestPublisherSubscriber.test_subscriber_terminates_in_a_finite_amount_of_time[Builtins]
test_communication.TestPublisherSubscriber.test_subscriber_terminates_in_a_finite_amount_of_time[Constants]
test_communication.TestPublisherSubscriber.test_subscriber_terminates_in_a_finite_amount_of_time[Defaults]
test_communication.TestPublisherSubscriber.test_subscriber_terminates_in_a_finite_amount_of_time[Empty]
test_communication.TestPublisherSubscriber.test_subscriber_terminates_in_a_finite_amount_of_time[MultiNested]
test_communication.TestPublisherSubscriber.test_subscriber_terminates_in_a_finite_amount_of_time[Nested]
test_communication.TestPublisherSubscriber.test_subscriber_terminates_in_a_finite_amount_of_time[Strings]
test_communication.TestPublisherSubscriber.test_subscriber_terminates_in_a_finite_amount_of_time[UnboundedSequences]
test_communication.TestPublisherSubscriber.test_subscriber_terminates_in_a_finite_amount_of_time[WStrings]
test_communication.TestPublisherSubscriber.test_subscriber_terminates_in_a_finite_amount_of_time[Arrays]
test_communication.TestPublisherSubscriber.test_subscriber_terminates_in_a_finite_amount_of_time[BasicTypes]
test_communication.TestPublisherSubscriber.test_subscriber_terminates_in_a_finite_amount_of_time[BoundedSequences]
test_communication.TestPublisherSubscriber.test_subscriber_terminates_in_a_finite_amount_of_time[Builtins]
test_communication.TestPublisherSubscriber.test_subscriber_terminates_in_a_finite_amount_of_time[Constants]
test_communication.TestPublisherSubscriber.test_subscriber_terminates_in_a_finite_amount_of_time[Defaults]
test_communication.TestPublisherSubscriber.test_subscriber_terminates_in_a_finite_amount_of_time[Empty]
test_communication.TestPublisherSubscriber.test_subscriber_terminates_in_a_finite_amount_of_time[MultiNested]
test_communication.TestPublisherSubscriber.test_subscriber_terminates_in_a_finite_amount_of_time[Nested]
test_communication.TestPublisherSubscriber.test_subscriber_terminates_in_a_finite_amount_of_time[Strings]
test_communication.TestPublisherSubscriber.test_subscriber_terminates_in_a_finite_amount_of_time[UnboundedSequences]
test_communication.TestPublisherSubscriber.test_subscriber_terminates_in_a_finite_amount_of_time[WStrings]
test_communication.TestPublisherSubscriber.test_subscriber_terminates_in_a_finite_amount_of_time[Arrays]
test_communication.TestPublisherSubscriber.test_subscriber_terminates_in_a_finite_amount_of_time[BasicTypes]
test_communication.TestPublisherSubscriber.test_subscriber_terminates_in_a_finite_amount_of_time[BoundedSequences]
test_communication.TestPublisherSubscriber.test_subscriber_terminates_in_a_finite_amount_of_time[Builtins]
test_communication.TestPublisherSubscriber.test_subscriber_terminates_in_a_finite_amount_of_time[Constants]
test_communication.TestPublisherSubscriber.test_subscriber_terminates_in_a_finite_amount_of_time[Defaults]
test_communication.TestPublisherSubscriber.test_subscriber_terminates_in_a_finite_amount_of_time[Empty]
test_communication.TestPublisherSubscriber.test_subscriber_terminates_in_a_finite_amount_of_time[MultiNested]
test_communication.TestPublisherSubscriber.test_subscriber_terminates_in_a_finite_amount_of_time[Nested]
test_communication.TestPublisherSubscriber.test_subscriber_terminates_in_a_finite_amount_of_time[Strings]
test_communication.TestPublisherSubscriber.test_subscriber_terminates_in_a_finite_amount_of_time[UnboundedSequences]
test_communication.TestPublisherSubscriber.test_subscriber_terminates_in_a_finite_amount_of_time[WStrings]
test_communication.TestPublisherSubscriber.test_subscriber_terminates_in_a_finite_amount_of_time[Arrays]
test_communication.TestPublisherSubscriber.test_subscriber_terminates_in_a_finite_amount_of_time[BasicTypes]
test_communication.TestPublisherSubscriber.test_subscriber_terminates_in_a_finite_amount_of_time[BoundedSequences]
test_communication.TestPublisherSubscriber.test_subscriber_terminates_in_a_finite_amount_of_time[Builtins]
test_communication.TestPublisherSubscriber.test_subscriber_terminates_in_a_finite_amount_of_time[Constants]
test_communication.TestPublisherSubscriber.test_subscriber_terminates_in_a_finite_amount_of_time[Defaults]
test_communication.TestPublisherSubscriber.test_subscriber_terminates_in_a_finite_amount_of_time[Empty]
test_communication.TestPublisherSubscriber.test_subscriber_terminates_in_a_finite_amount_of_time[MultiNested]
test_communication.TestPublisherSubscriber.test_subscriber_terminates_in_a_finite_amount_of_time[Nested]
test_communication.TestPublisherSubscriber.test_subscriber_terminates_in_a_finite_amount_of_time[Strings]
test_communication.TestPublisherSubscriber.test_subscriber_terminates_in_a_finite_amount_of_time[UnboundedSequences]
test_communication.TestPublisherSubscriber.test_subscriber_terminates_in_a_finite_amount_of_time[WStrings]
```

Failure message:

```
Traceback (most recent call last):
  File "/home/jenkins-agent/workspace/nightly_linux_debug/ws/build/test_communication/test_publisher_subscriber__rclpy__rmw_connext_cpp__rmw_fastrtps_cpp_Debug.py", line 66, in test_subscriber_terminates_in_a_finite_amount_of_time
    proc_info.assertWaitForShutdown(process=subscriber_process, timeout=10)
  File "/home/jenkins-agent/workspace/nightly_linux_debug/ws/install/launch_testing/lib/python3.6/site-packages/launch_testing/proc_info_handler.py", line 144, in assertWaitForShutdown
    assert success, "Timed out waiting for process '{}' to finish".format(process)
AssertionError: Timed out waiting for process '<launch.actions.execute_process.ExecuteProcess object at 0x7f16457296a0>' to finish
```

**Comment by dirk-thomas** [comment] 2020-02-20 18:04
Duplicate of eProsima/Fast-RTPS#1014 which has already been resolved.

**Closed by dirk-thomas** 2020-02-20 18:04 UTC
