### ISSUE TITLE
New failing test: test_client_scope_cpp__rmw_connext_cpp

### ISSUE THREAD

**Issue by clalancette** [ros2/system_tests#212] opened 2017-06-27 14:06 UTC
Starting with build: http://ci.ros2.org/view/nightly/job/nightly_linux_repeated/696/ , the test known as test_client_scope_cpp__rmw_connext_cpp started failing.  If you search for 'test_client_scope_cpp' in the console output, you'll see that this test started timing out.

**Comment by mikaelarguedas** [comment] 2017-06-27 17:08
known to be flaky

**Comment by dhood** [comment] 2018-03-01 19:15
closing as duplicate of https://github.com/ros2/build_cop/issues/41

**Comment by dhood** [comment] 2018-03-01 19:19
actually I think I might have been incorrect that it was tracked by the other ticket, it seems that https://github.com/ros2/build_cop/issues/41 only refers to fastrtps. services are known to take up to 20s on connext, so maybe increasing the timeout is enough for that test (it starts two clients). I'll check if that makes a difference.

**Closed** 2018-03-09 18:16 UTC
Labels: duplicate, in progress
